### ISSUE TITLE
can't make this chart work off the shelve

### ISSUE THREAD

**Issue by MarcMielke** [localstack/helm-charts#60]
Whatever I do I get this:
```
2022-09-13T10:32:50.898 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_serializer_handlers is disabled
2022-09-13T10:32:50.898 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_pro_infra = <function setup_pro_infra at 0x7f028edb0f70>)
2022-09-13T10:32:50.898 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:setup_pro_infra is disabled
Error starting infrastructure: expected str, bytes or os.PathLike object, not NoneType Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/core.py", line 183, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/runtime/init.py", line 197, in _run_init_scripts_on_start
    _run_and_log(Stage.START)
  File "/opt/code/localstack/localstack/runtime/init.py", line 214, in _run_and_log
    scripts = init_script_manager().run_stage(stage)
  File "/opt/code/localstack/localstack/runtime/init.py", line 124, in run_stage
    scripts = self.scripts.get(stage, [])
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/code/localstack/localstack/runtime/init.py", line 106, in scripts
    return self._find_scripts()
  File "/opt/code/localstack/localstack/runtime/init.py", line 161, in _find_scripts
    stage_path = os.path.join(self.script_root, stage_dir)
  File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any hints/ ideas?

Context: Targeted platform is k3s on DDFM.

Not a python guy but it looks like this tries to open a non-existent file? Guessing from this link: https://bobbyhadz.com/blog/python-typeerror-expected-str-bytes-or-os-pathlike-object-not-nonetype#:~:text=The%20Python%20%22TypeError%3A%20expected%20str,from%20and%20correct%20the%20assignment.

**Comment by whummer** [comment]
Hi @MarcMielke , thanks for reporting. Just gave it a try with the latest chart version, and haven't been able to replicate this issue:

```
$ helm install test localstack/localstack
...
$ kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services test-localstack
31566
$ curl localhost:31566/health
{"features": {"initScripts": "initialized"}, "services": {"acm", ... 
```

Can you please share the full logs of the LocalStack pod / container? Also, perhaps it helps if you manually pull the `latest` version of the `localstack/localstack` Docker image? Please keep us posted on how it goes, thanks!

**Comment by whummer** [comment]
Hi @MarcMielke , quick update - looks like we have been able to replicate this issue, a fix has been pushed in https://github.com/localstack/localstack/pull/6924 . Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
