### ISSUE TITLE
Unable to launch with default settings

### ISSUE THREAD

**Issue by absa-rsuarez** [localstack/helm-charts#65]
Trying to launch the latest and several prior versions of the chart and getting the below:

`2022-10-31T20:15:56.048 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='transfer:pro', value='localstack_ext.providers:transfer', group='localstack.aws.provider')
2022-10-31T20:15:56.048 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='xray:pro', value='localstack_ext.providers:xray', group='localstack.aws.provider')
2022-10-31T20:15:56.049 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Cleaning up resources ...
2022-10-31T20:15:56.050 DEBUG --- [  MainThread] localstack.utils.threads   : [shutdown] Done cleaning up threads / processes / tasks
2022-10-31T20:15:56.050 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: rm -rf "/var/lib/localstack/tmp"
2022-10-31T20:15:56.058 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Force shutdown, not waiting for infrastructure to shut down
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/code/localstack/localstack/cli/main.py", line 10, in <module>
    main()
  File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 148, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 260, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 435, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 421, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 520, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 512, in start_runtime_components
    raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
2022-10-31 20:15:57,369 INFO exited: infra (exit status 1; not expected)`

These are the only parameters that have been set based on other reported issues:
`
  set {
    name  = "livenessProbe.periodSeconds"
    value = "65"
  }
  set {
    name  = "debug"
    value = "true"
  }
`

**Comment by navneel99** [comment]
Is this issue solved? This is an intermittent error I get everytime a new release happens.

**Comment by alexrashed** [comment]
Hi @navneel99!
Could you please create a new issue report with a detailed description of your issue and how to reproduce it?
Thanks!

**Comment by absa-rsuarez** [comment]
My issue ended up being something to do with the proxy internally...After I exported the ENV Vars to set the proxy it was able to start. I also needed to increase the liveness probe to 180 seconds to give the app enough time to launch successfully.

**Comment by navneel99** [comment]
Hi @alexrashed, sorry for the very late response. My issue also got resolved once I exported the proxy environment variables.
